name: amplify_trips_planner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  amplify_api: ^0.6.0
  amplify_auth_cognito: ^0.6.0
  amplify_authenticator: ^0.2.2
  amplify_datastore: ^0.6.0
  amplify_flutter: ^0.6.0
  amplify_storage_s3: ^0.6.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^1.0.4
  go_router: ^4.1.0
  hooks_riverpod: ^1.0.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0

dev_dependencies:
  amplify_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/amplify.png
